services:
  postgres:
    image: postgres:15
    container_name: tt_players_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tt_players
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
