export { db, createDb } from './database.js';
export type { Database } from './types.js';
export type {
    // Enum types
    CompetitionType,
    FixtureStatus,
    OutcomeType,
    ScrapeStatus,
    // Table row types
    Platform,
    NewPlatform,
    PlatformUpdate,
    League,
    NewLeague,
    LeagueUpdate,
    Season,
    NewSeason,
    SeasonUpdate,
    Competition,
    NewCompetition,
    CompetitionUpdate,
    Team,
    NewTeam,
    TeamUpdate,
    ExternalPlayer,
    NewExternalPlayer,
    ExternalPlayerUpdate,
    LeagueStanding,
    NewLeagueStanding,
    LeagueStandingUpdate,
    Fixture,
    NewFixture,
    FixtureUpdate,
    Rubber,
    NewRubber,
    RubberUpdate,
    RawScrapeLog,
    NewRawScrapeLog,
    RawScrapeLogUpdate,
    CacheEntry,
    NewCacheEntry,
    CacheEntryUpdate,
} from './types.js';
